spring.datasource.url=jdbc:mysql://localhost:3306/plango
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.sql.init.mode=never

# JSP view resolver
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# Session timeout untuk login JSP
server.servlet.session.timeout=30m

server.port=8080
